name: avr-tools

on:
  push:
    paths:
      - 'avr/**'
  schedule:
      - cron:  '0 12 7 * *'

env:
  CROSSTOOL_NG_VERSION: "1.24.0"
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_REGISTRY_REPOSITORY: "${{ secrets.DOCKER_HUB_ORG }}/${{ github.workflow }}"
  GITHUB_DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
  GITHUB_DOCKER_REGISTRY: docker.pkg.github.com
  GITHUB_DOCKER_REGISTRY_REPOSITORY: "docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}"

jobs:

  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Login
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u $GITHUB_DOCKER_USERNAME -p ${{ secrets.GITHUB_DOCKER_PASSWORD }} $GITHUB_DOCKER_REGISTRY

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build avr-gcc
      run: "
           cd avr
        && docker build
            --target tools
            --tag local-tools
            --build-arg CROSSTOOL_NG_VERSION
            -f Dockerfile .
        "

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: |
        VERSION=`docker run --rm  local-tools  bash -c "avr-gcc -v 2>&1 | tail -n1 | sed -e 's:^[^1234567890]*::' -e 's:[^1234567890]*$::'"`

        docker tag local-tools $DOCKER_HUB_REGISTRY_REPOSITORY:$VERSION
        docker tag local-tools $DOCKER_HUB_REGISTRY_REPOSITORY:latest
        docker tag local-tools $GITHUB_DOCKER_REGISTRY_REPOSITORY:latest

        docker push $DOCKER_HUB_REGISTRY_REPOSITORY:$VERSION
        docker push $DOCKER_HUB_REGISTRY_REPOSITORY:latest
        docker push $GITHUB_DOCKER_REGISTRY_REPOSITORY:latest
