name: esp-tools

on:
  push:
    paths:
      - 'esp/tools/**'
  schedule:
      - cron: '0 10 * * WED'

env:
  IDF_BRANCH: "release/v4.0"
  TOOLCHAIN_BRANCH: "esp-2019r2"
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_REGISTRY_REPOSITORY: "${{ secrets.DOCKER_HUB_ORG }}/${{ github.workflow }}"
  GITHUB_DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
  GITHUB_DOCKER_REGISTRY: docker.pkg.github.com
  GITHUB_DOCKER_REGISTRY_REPOSITORY: "docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}"

jobs:

  build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Login
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login -u $GITHUB_DOCKER_USERNAME -p ${{ secrets.GITHUB_DOCKER_PASSWORD }} $GITHUB_DOCKER_REGISTRY

    - name: Checkout
      uses: actions/checkout@v1
      with:
        lfs: true

    - name: Build xtensa-gcc
      run: "
           cd esp/tools
        && docker build
            --pull
            --target tools-xtensa-gcc
            --tag local-tools-gcc
            --build-arg IDF_BRANCH
            --build-arg TOOLCHAIN_BRANCH
            -f Dockerfile .
        "

    - name: Build esp
      run: "
           cd esp/tools
        && docker build
            --target tools
            --tag local-tools
            --build-arg IDF_BRANCH
            --build-arg TOOLCHAIN_BRANCH
            --cache-from local-tools-gcc
            -f Dockerfile .
        "

    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: |
        docker run --rm -v $PWD:/root/share  local-tools  bash -c "cp -rf \$IDF_PATH/version.txt \$IDF_PATH/tag.txt /root/share/"

        TAG=`cat tag.txt`
        VERSION=`cat version.txt`

        docker tag local-tools $DOCKER_HUB_REGISTRY_REPOSITORY:$VERSION
        docker tag local-tools $DOCKER_HUB_REGISTRY_REPOSITORY:$TAG
        docker tag local-tools $DOCKER_HUB_REGISTRY_REPOSITORY:latest
        docker tag local-tools $GITHUB_DOCKER_REGISTRY_REPOSITORY:latest

        docker push $DOCKER_HUB_REGISTRY_REPOSITORY:$VERSION
        docker push $DOCKER_HUB_REGISTRY_REPOSITORY:$TAG
        docker push $DOCKER_HUB_REGISTRY_REPOSITORY:latest
        docker push $GITHUB_DOCKER_REGISTRY_REPOSITORY:latest
